# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
base_branches:
  exclude:
    - "main"
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  fail_commit_status: true
  collapse_walkthrough: true
  auto_apply_labels: true
  poem: true
  review_status: true
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
  