name: Validate Commit Was Deployed to Staging

on:
    pull_request:
        branches:
            - release/**

jobs:
    check-stage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Check if commit exists on 'stage'
              run: |
                git fetch origin stage
                if git merge-base --is-ancestor $GITHUB_SHA origin/stage; then
                    echo "HEAD commit is on stage"
                else
                    echo "HEAD commit not on stage - must be deployed to staging first"
                    exit 1
                fi
