name: Events RSS Feed Cron Job

on:
  schedule:
    - cron: "45 3 * * *"
  workflow_dispatch:
  
jobs:
  run-RSS-Runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create virtual environment and Install dependencies
        run: |
          chmod +x setup.sh
          ./setup.sh
      
      - name: Update runningCSV.csv with Information Session Events
        env:
          TASK_TYPE: "INFO-SESSION"
          EVENTS_RSS_URL: ${{ secrets.INFO_SESSION_RSS }}
        run: |
          source .virtualenv/bin/activate
          python -m data_collections.mainRSSRunner

      - name: Commit & push changes if any
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          if ! git diff --quiet; then
            git add data_collections/runningCSV.csv
            git commit -m 'Update runningCSV.csv'
            git push origin main
          else
            echo "No changes to commit."
          fi
