name: Spell and Grammar Checker
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check Spelling
        uses: check-spelling/check-spelling@v0.0.24
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Install Vale
        run: |
          VALE_VERSION="2.29.4"  
          curl -fsSL "https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz" \  
            | tar --strip-components=1 -xz -C /tmp
          sudo install -m 0755 /tmp/vale /usr/local/bin/vale

      - name: Run Vale (Grammar Check)
        run: /usr/local/bin/vale .
        continue-on-error: true