name: Spell and Grammar Checker
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check Spelling
        uses: check-spelling/check-spelling@v0.0.24
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Install Vale
        run: |
          snap install vale | tar -xz -C /usr/local/bin vale

      - name: Run Vale (Grammar Check)
        run: |
          /usr/local/bin/vale . || true  # '|| true' to prevent workflow failure on errors