name: Update stage branch from main
on:
  schedule:
      - cron: "0 4 1,15 * *"
  workflow_dispatch:

jobs:
  flatten-stage-with-prod:
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: main
      TARGET_BRANCH: stage
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    steps:
      - name: Read GPG Key
        run: |
          echo -n "${{ secrets.GPG_SIGNING_KEY }}" | base64 --decode | gpg --import
      - name: Set up GPG for commit signing
        run: |
          git config --global user.signingkey $GPG_KEY_ID
          git config --global commit.gpgsign true
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SOURCE_BRANCH }}
          fetch-depth: 0

      - name: Push ${{ env.SOURCE_BRANCH }} to ${{ env.TARGET_BRANCH }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin --prune
          echo "Pushing $(git rev-parse --short HEAD) to ${TARGET_BRANCH}"
          git push --force-with-lease origin ${SOURCE_BRANCH}:refs/heads/${TARGET_BRANCH}
      - name: checkout repository
        uses: actions/checkout@v4
        with: 
          ref: main
          fetch-depth: 0
      
      - name: Push main to stage
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git fetch origin --prune
          # Push main to stage, but refuse if origin/stage moved unexpectedly
          git push --force-with-lease origin main:refs/heads/stage


    