name: Update stage branch from main
on:
  schedule:
      - cron: "0 4 1,15 * *"
  workflow_dispatch:

jobs:
  flatten-stage-with-prod:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with: 
          ref: main
          fetch-depth: 0
      
      - name: Push main to stage
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git fetch origin --prune
          # Push main to stage, but refuse if origin/stage moved unexpectedly
          git push --force-with-lease origin main:refs/heads/stage


    